language: node_js
node_js:
  - "0.10"
sudo: required
before_install:
  - "curl -L http://git.io/ejPSng | /bin/sh"
  - "rm -r node.js/benchmark/ node.js/deps/ node.js/doc/ node.js/src/ node.js/test/ node.js/tools/"
